# Generated by Django 2.1.2 on 2019-07-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Сообщение'),
        ),
    ]
